"""Request, response, draft and proposal contracts (BUILD_SPEC §7, AM-10, AM-11, AM-13, AM-80).

Every model is strict, frozen and closed (`extra="forbid"`): the server sets actor, tenant, roles, timestamps and
authority fields, and a body that tries to supply them is rejected before any handler runs (R004). Bodies are parsed
with `load()` (JSON mode) so numbers are never coerced from strings or booleans. The JSON Schemas under `schemas/`
say the same things declaratively (they are generated by `scripts/build_schemas.py`);
`tests/plan_c/test_schema_conformance.py` keeps the two in step.

Timestamps (plan ruling 6): every instant must carry a zero UTC offset. Inputs may spell it `Z` or `+00:00`; the
hashed and stored form is pydantic's JSON output, which spells it `Z`, so the proposal schema accepts only `Z` while
request schemas accept either spelling.
"""

from __future__ import annotations

from datetime import UTC
from enum import StrEnum
from typing import Annotated, Any, Final, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, StringConstraints, field_validator, model_validator

from ops_core.canonical import canonical_sha256
from ops_core.states import AttemptState, Intent, RunState

AUTHORITY_FIELDS: Final = frozenset(
    {
        "tenant_id",
        "actor",
        "actor_id",
        "role",
        "roles",
        "approved",
        "approved_by",
        "destination",
        "reviewer",
        "requester",
    }
)  # names a client or model may never supply (BUILD_SPEC §7, R004); `extra="forbid"` rejects them everywhere

_Strict = ConfigDict(frozen=True, extra="forbid", strict=True)
Text = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=4000)]
Short = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=500)]
Title = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=120)]
Summary = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=2500)]
AssetId = Annotated[str, StringConstraints(pattern=r"^[A-Z][A-Z0-9_-]{0,31}$")]
EvidenceRef = Annotated[str, StringConstraints(min_length=1, max_length=160)]
Sha256 = Annotated[str, StringConstraints(pattern=r"^[a-f0-9]{64}$")]


def load[M: BaseModel](model: type[M], text: str) -> M:
    """Parse a JSON body into a contract in strict JSON mode (strings never become numbers, bools never ints)."""
    return model.model_validate_json(text)


def _unique(items: list[str]) -> list[str]:
    if len(set(items)) != len(items):
        raise ValueError("duplicate entries")
    return items


def _sorted(items: list[str], what: str) -> None:
    # Canonical JSON keeps array order (BUILD_SPEC §6 "documented stable array order"), so the producer must fix it.
    if items != sorted(items):
        raise ValueError(f"{what} must be sorted ascending by code point so the payload hash is stable")


def _utc(value: AwareDatetime) -> AwareDatetime:
    # BUILD_SPEC §6 "UTC instants with explicit offsets": a zero offset is required (`Z` or `+00:00` both parse to
    # it), so one instant has one canonical spelling once pydantic serialises it as `Z` (ruling 6).
    if value.utcoffset() != UTC.utcoffset(None):
        raise ValueError("timestamps must carry a zero UTC offset (Z or +00:00)")
    return value


class MessageKind(StrEnum):
    """What a message asks for; the admission router (AM-16) reads it."""

    INVESTIGATE = "investigate"
    ASK = "ask"
    STATUS = "status"
    CLARIFICATION = "clarification"


class MessageContext(BaseModel):
    """Structured context a requester may attach: the asset and the look-back window in hours."""

    model_config = _Strict
    asset_id: AssetId | None = None
    hours: int | None = Field(default=None, ge=1, le=168)  # strict: True, 1.5 and "24" are rejected


class MessageRequest(BaseModel):
    """`POST /conversations/{id}/messages` (BUILD_SPEC §7 sample; AM-16 admission routes read `kind`)."""

    model_config = _Strict
    kind: MessageKind
    text: Text
    context: MessageContext | None = None
    supersedes_run_id: UUID | None = None  # requester-asserted (AM-10 "Requester-asserted fields")


class RunRequestFields(BaseModel):
    """The requester-asserted run fields `create_run`/`create_revision` store on `runs` (AM-10, AM-20.3).

    They come only from the authenticated request's structured fields (admission or revision); model output is never
    a source for either, which is why `ModelDraft` has neither field. `intent` drives `freeze_allowed`;
    `supersedes_run_id` is injected into the hashed payload by `freeze_proposal`.
    """

    model_config = _Strict
    intent: Intent
    supersedes_run_id: UUID | None = None


class ClarificationReply(BaseModel):
    """The requester's answer to a clarification question (AM-10 clarification signal)."""

    model_config = _Strict
    question_id: UUID
    expected_version: int = Field(ge=1)
    context: MessageContext

    @model_validator(mode="after")
    def _answers_something(self) -> ClarificationReply:
        if self.context.asset_id is None and self.context.hours is None:
            raise ValueError("a clarification reply must supply asset_id or hours")
        return self


class DecisionRequest(BaseModel):
    """`POST /proposals/{id}/decisions`; the reviewer is the session, never a field (BUILD_SPEC §13)."""

    model_config = _Strict
    expected_revision: int = Field(ge=1)
    expected_payload_sha256: Sha256  # AM-11 / AM-80 row 14 (renamed from payload_sha256)
    decision: Literal["approve", "reject"]
    reason: Annotated[str, StringConstraints(max_length=500)] | None = None


class RevisionRequest(BaseModel):
    """`POST /runs/{id}/revisions`: re-queue a run, optionally naming the run it supersedes (AM-20.3)."""

    model_config = _Strict
    expected_version: int = Field(ge=1)
    supersedes_run_id: UUID | None = None


class CancelRequest(BaseModel):
    """`POST /runs/{id}/cancel` body (schemas/cancellation.schema.json)."""

    model_config = _Strict
    expected_version: int = Field(ge=1)
    reason: Annotated[str, StringConstraints(max_length=500)] | None = None


class CancelResponse(BaseModel):
    """`POST /runs/{id}/cancel` reports whether a grant or dispatch already happened; it never claims undo (AM-13)."""

    model_config = _Strict
    run_id: UUID
    status: RunState
    state_version: int = Field(ge=1)
    cancel_requested: bool
    grant_exists: bool
    attempt_state: AttemptState | None
    note: Short | None

    @model_validator(mode="after")
    def _attempt_only_with_grant(self) -> CancelResponse:
        if not self.grant_exists and self.attempt_state is not None:
            raise ValueError("an attempt state exists only after a grant")
        return self


class FeedbackRequest(BaseModel):
    """`POST /runs/{id}/feedback`: classified, stored, never a runtime policy (R113)."""

    model_config = _Strict
    subject_kind: Literal["run", "proposal", "event"]
    subject_id: UUID
    category: Literal["wrong_evidence", "missing_evidence", "wrong_conclusion", "unclear", "other"]
    text: Annotated[str, StringConstraints(max_length=2000)] | None = None


class ManualProposalRequest(BaseModel):
    """`POST /manual-proposals`: a human-authored draft that enters the same approval path (AM-20.3)."""

    model_config = _Strict
    asset_id: AssetId
    start_at: AwareDatetime
    end_at: AwareDatetime
    title: Title
    summary: Summary
    evidence_refs: Annotated[list[EvidenceRef], Field(min_length=1, max_length=8)]
    assumptions: Annotated[list[Short], Field(max_length=8)]
    limitations: Annotated[list[Short], Field(max_length=8)]

    @field_validator("start_at", "end_at")
    @classmethod
    def _utc_only(cls, value: AwareDatetime) -> AwareDatetime:
        return _utc(value)

    @field_validator("evidence_refs")
    @classmethod
    def _unique_refs(cls, items: list[str]) -> list[str]:
        return _unique(items)

    @model_validator(mode="after")
    def _interval(self) -> ManualProposalRequest:
        if not self.start_at < self.end_at:
            raise ValueError("start_at must be before end_at")
        return self


class ModelDraft(BaseModel):
    """The validated model output (schemas/model-draft.schema.json). Carries no authority and no supersession."""

    model_config = _Strict
    kind: Literal["proposal", "answer", "abstain"]
    title: Title
    summary: Summary
    evidence_refs: Annotated[list[EvidenceRef], Field(max_length=8)]
    assumptions: Annotated[list[Short], Field(max_length=8)]
    limitations: Annotated[list[Short], Field(max_length=8)]
    question: Short | None = None  # AM-10: abstain + question = clarification; abstain alone = insufficient evidence

    @field_validator("evidence_refs")
    @classmethod
    def _unique_refs(cls, items: list[str]) -> list[str]:
        return _unique(items)

    @model_validator(mode="after")
    def _kind_rules(self) -> ModelDraft:
        if self.kind in {"proposal", "answer"} and not self.evidence_refs:
            raise ValueError(f"a {self.kind} cites at least one piece of evidence")
        if self.question is not None and self.kind != "abstain":
            raise ValueError("only an abstain carries a question")
        return self

    @property
    def clarification_requested(self) -> bool:
        return self.kind == "abstain" and self.question is not None


class SourceSnapshot(BaseModel):
    """The version and hash of one cited evidence item at freeze time."""

    model_config = _Strict
    evidence_id: EvidenceRef
    content_sha256: Sha256
    version: Annotated[str, StringConstraints(min_length=1, max_length=40)]


class ProposalPayload(BaseModel):
    """The hashed payload (BUILD_SPEC §6 list; AM-80 row 19). `authored_by` is NOT here: it is a sibling of payload."""

    model_config = _Strict
    tenant_id: UUID
    run_id: UUID
    proposal_id: UUID
    revision: int = Field(ge=1)
    action: Literal["create_incident"]
    destination: Literal["synthetic-incidents"]
    asset_id: AssetId
    start_at: AwareDatetime
    end_at: AwareDatetime
    title: Title
    summary: Summary
    evidence_refs: Annotated[list[EvidenceRef], Field(min_length=1, max_length=8)]
    source_snapshots: Annotated[list[SourceSnapshot], Field(min_length=1, max_length=8)]
    assumptions: Annotated[list[Short], Field(max_length=8)]
    limitations: Annotated[list[Short], Field(max_length=8)]
    workflow_version: Annotated[str, StringConstraints(min_length=1, max_length=60)]
    prompt_version: Annotated[str, StringConstraints(min_length=1, max_length=60)]
    expires_at: AwareDatetime
    supersedes_run_id: UUID | None = None  # injected by freeze_proposal from runs (AM-20.3); inside the hash (R125)

    @field_validator("start_at", "end_at", "expires_at")
    @classmethod
    def _utc_only(cls, value: AwareDatetime) -> AwareDatetime:
        return _utc(value)

    @field_validator("evidence_refs")
    @classmethod
    def _unique_sorted_refs(cls, items: list[str]) -> list[str]:
        _sorted(items, "evidence_refs")
        return _unique(items)

    @field_validator("source_snapshots")
    @classmethod
    def _snapshots_sorted(cls, items: list[SourceSnapshot]) -> list[SourceSnapshot]:
        _sorted([s.evidence_id for s in items], "source_snapshots (by evidence_id)")
        return items

    @model_validator(mode="after")
    def _interval(self) -> ProposalPayload:
        if not self.start_at < self.end_at:
            raise ValueError("start_at must be before end_at")
        return self

    def canonical_dict(self) -> dict[str, Any]:
        """Return the JSON-ready mapping that is hashed.

        UUIDs become strings and UTC timestamps pydantic's `…Z` form (ruling 6), whatever spelling the input used;
        None fields are omitted so an absent supersedes_run_id and a missing one hash alike. Arrays are already in
        their validated sorted order.
        """
        return self.model_dump(mode="json", exclude_none=True)


class Proposal(BaseModel):
    """An immutable revision: canonical bytes' hash plus the content authors, kept outside the hash (AM-80)."""

    model_config = _Strict
    canonicalization_version: Literal[1]
    payload: ProposalPayload
    payload_sha256: Sha256
    authored_by: list[UUID] = Field(min_length=1, max_length=8)  # requester plus revision authors (AM-20.3)

    @model_validator(mode="after")
    def _hash_matches(self) -> Proposal:
        expected = canonical_sha256(self.payload.canonical_dict())
        if self.payload_sha256 != expected:
            raise ValueError(f"payload_sha256 {self.payload_sha256} does not match the canonical bytes ({expected})")
        return self


class ErrorCode(StrEnum):
    """The documented error codes (BUILD_SPEC §7 plus the AM-80 error row)."""

    UNAUTHENTICATED = "UNAUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    INVALID_INPUT = "INVALID_INPUT"
    RATE_LIMITED = "RATE_LIMITED"
    UNAVAILABLE = "UNAVAILABLE"
    ASSET_ACTION_UNRESOLVED = "ASSET_ACTION_UNRESOLVED"
    ASSET_INCIDENT_EXISTS = "ASSET_INCIDENT_EXISTS"
    GRANT_EXISTS = "GRANT_EXISTS"
    SLOT_OCCUPIED = "SLOT_OCCUPIED"
    AUTHORITY_VIOLATION = "AUTHORITY_VIOLATION"


class SafeError(BaseModel):
    """BUILD_SPEC §7 safe error: no stack traces, queries, tokens or unauthorized IDs."""

    model_config = _Strict
    code: ErrorCode
    message: Short
    retryable: bool
    request_id: UUID
