"""Dev bootstrap (T05): generate secrets outside git, write .env, bring the Compose dev profile up.

Usage:
    uv run python scripts/bootstrap_dev.py secrets          # generate missing secret files and .env (idempotent)
    uv run python scripts/bootstrap_dev.py up               # secrets + `docker compose --profile dev up -d --wait`
    uv run python scripts/bootstrap_dev.py down             # stop containers, keep volumes (never -v)
    uv run python scripts/bootstrap_dev.py status           # `docker compose --profile dev ps`

Secrets live under %LOCALAPPDATA%\\ops-copilot\\secrets (override with OPS_SECRETS_DIR). Nothing here prints a secret.
"""

from __future__ import annotations

import json
import os
import secrets as _secrets
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Iterable
from pathlib import Path

# Must equal the top-level `secrets:` keys of compose.yaml; tests/plan_b/test_bootstrap_dev.py enforces it.
SECRET_NAMES: tuple[str, ...] = (
    "postgres_password",
    "postgres_incident_password",
    "kc_bootstrap_admin_password",
    "kc_client_secret_ops_web",
    "kc_client_secret_ops_worker",
    "kc_client_secret_ops_mcp_read",
    "kc_client_secret_ops_mcp_write",
    "kc_persona_alex_password",
    "kc_persona_sam_password",
    "kc_client_secret_ops_view_users",
    "kc_persona_lee_password",
    "kc_persona_riley_password",
    "kc_persona_jordan_password",
    # One login per AM-20.1 role (T09); read by scripts/skeleton.py migrate and by each service, never mounted.
    "postgres_api_password",
    "postgres_worker_password",
    "postgres_sweeper_password",
    "postgres_mcp_read_password",
    "postgres_mcp_exec_password",
    "postgres_operator_password",
    "postgres_test_harness_password",
    # T11: the API's Fernet key material for sealed provider tokens, and the dev/test-only admin client the live
    # suite uses to disable and re-enable a persona (ruling 18). Only the Keycloak client secret is mounted (the
    # entrypoint exports it for the realm import); the session key is read from the host.
    "api_session_key",
    "kc_client_secret_ops_test_admin",
)
ENV_PATH = Path(".env")
# Non-default high ports keep clear of a local PostgreSQL (5432) or another Keycloak/web server (8080) on the host.
KC_HTTP_PORT = 18080
PG_PORT = 15432
MCP_READ_RESOURCE_URL = "http://mcp-read:8081/mcp"
MCP_WRITE_RESOURCE_URL = "http://mcp-write:8082/mcp"
OLLAMA_BASE_URL_HOST = "http://127.0.0.1:11434"
OLLAMA_BASE_URL_CONTAINER = "http://host.docker.internal:11434"


def secrets_dir() -> Path:
    """Return the directory that holds secret files: OPS_SECRETS_DIR if set, else a per-user path outside the repo.

    Keeping the default outside the working tree means a stray `git add -A` can never stage a secret.
    """
    override = os.environ.get("OPS_SECRETS_DIR")
    if override:
        return Path(override)
    base = os.environ.get("LOCALAPPDATA") or str(Path.home() / ".local" / "share")
    return Path(base) / "ops-copilot" / "secrets"


def generate_secrets(directory: Path, names: Iterable[str]) -> list[str]:
    """Create each missing secret file with 43 URL-safe chars (32 random bytes), no newline. Existing files are kept.

    Never overwriting makes the bootstrap safe to re-run: regenerating a secret would lock the owner out of a
    PostgreSQL volume that was initialised with the old password. The file holds exactly the value, with no trailing
    newline: readers that strip newlines (`cat` in a shell substitution, the entrypoint) do not care, but raw readers
    such as `Path.read_text` in the live `secret` fixture would otherwise see the newline as part of the secret.

    Returns:
        The names of the files created on this call (empty on a repeat run).
    """
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    created: list[str] = []
    for name in names:
        path = directory / name
        if path.exists():
            continue
        # O_EXCL: never overwrite an existing secret even if two bootstraps race (the loser gets FileExistsError and
        # keeps the winner's file); 0o600: owner-only. On Windows the mode bits are advisory (NTFS ACLs apply, and
        # %LOCALAPPDATA% is already user-private); on POSIX they are the control.
        try:
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError:
            continue
        with os.fdopen(fd, "wb") as fh:
            fh.write(_secrets.token_urlsafe(32).encode("ascii"))
        created.append(name)
    return created


def write_env(path: Path, secrets_directory: Path) -> None:
    """Write the git-ignored `.env` that Compose reads: paths, ports and URLs only, never a secret value."""
    lines = [
        "# Generated by scripts/bootstrap_dev.py. Paths, ports and URLs only; secrets are files under OPS_SECRETS_DIR.",
        # as_posix(): Compose accepts forward slashes on Windows, and backslashes would be read as escapes in .env.
        f"OPS_SECRETS_DIR={secrets_directory.resolve().as_posix()}",
        f"KC_HTTP_PORT={KC_HTTP_PORT}",
        f"PG_PORT={PG_PORT}",
        f"MCP_READ_RESOURCE_URL={MCP_READ_RESOURCE_URL}",
        f"MCP_WRITE_RESOURCE_URL={MCP_WRITE_RESOURCE_URL}",
        f"OLLAMA_BASE_URL_HOST={OLLAMA_BASE_URL_HOST}",
        f"OLLAMA_BASE_URL_CONTAINER={OLLAMA_BASE_URL_CONTAINER}",
    ]
    # newline="\n": on Windows text mode would otherwise write CRLF, which Compose would carry into values.
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def delete_bootstrap_admin(base_url: str, username: str, password: str) -> str:
    """Delete the temporary master-realm admin using its own token (T43). Returns 'deleted' or 'absent'.

    Keycloak creates `tmpadmin` only to get the first login; leaving a master-realm admin with a file-based password
    in place would be a standing superuser. Keycloak 26.8 answers the password grant for a deleted user with
    HTTP 400 `invalid_grant` (measured 2026-10-08); 401 is accepted too in case a later version changes it. A 400
    also follows a wrong password (for example a rotated secret file while the admin still exists), so 'absent' means
    "already deleted" only because the documented rotation (`down`/`up`, ephemeral Keycloak data) makes the two cases
    coincide; that is what keeps a repeat `up` idempotent. A 5xx, a connection error or a 404 on the DELETE
    deliberately raise: a failed security cleanup must be loud, even though `compose up` already succeeded.
    """
    form = urllib.parse.urlencode(
        {"grant_type": "password", "client_id": "admin-cli", "username": username, "password": password}
    ).encode("ascii")
    try:
        with urllib.request.urlopen(f"{base_url}/realms/master/protocol/openid-connect/token", form, timeout=20) as r:
            token = json.loads(r.read())["access_token"]
    except urllib.error.HTTPError as exc:
        if exc.code in (400, 401):
            return "absent"
        raise
    auth = {"Authorization": f"Bearer {token}"}
    # exact=true: without it Keycloak substring-matches usernames, so a `tmpadmin2` would be deleted too.
    q = urllib.parse.urlencode({"username": username, "exact": "true"})
    with urllib.request.urlopen(
        urllib.request.Request(f"{base_url}/admin/realms/master/users?{q}", headers=auth), timeout=20
    ) as r:
        users = json.loads(r.read())
    for u in users:
        req = urllib.request.Request(f"{base_url}/admin/realms/master/users/{u['id']}", headers=auth, method="DELETE")
        with urllib.request.urlopen(req, timeout=20):
            pass
    return "deleted" if users else "absent"


def compose(*args: str) -> int:
    """Run `docker compose --profile dev <args>` and return its exit code (the command line is echoed, no secrets)."""
    cmd = ["docker", "compose", "--profile", "dev", *args]
    print("$", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=False).returncode


def main(argv: list[str]) -> int:
    """Run one sub-command (secrets, up, down, status); return the process exit code, 2 for an unknown command.

    Every sub-command, `down` and `status` included, first (idempotently) generates any missing secret files and
    rewrites `.env`, so the Compose variables always resolve.
    """
    command = argv[0] if argv else "secrets"
    if command not in {"secrets", "up", "down", "status"}:
        print(__doc__)
        return 2
    directory = secrets_dir()
    created = generate_secrets(directory, SECRET_NAMES)
    write_env(ENV_PATH, directory)
    print(f"secrets: {len(created)} created, {len(SECRET_NAMES) - len(created)} kept, in {directory}")
    print(f".env written: {ENV_PATH.resolve()}")
    if command == "up":
        rc = compose("up", "-d", "--wait", "--wait-timeout", "240")
        if rc == 0:
            # The temporary master-realm admin is only needed to bootstrap; remove it with its own token (T43).
            # Strip like the entrypoint's `$(cat ...)` does: a hand-edited file with a trailing newline would otherwise
            # send a different password than Keycloak holds, get a 400 and report "absent" while tmpadmin still exists.
            secret = (directory / "kc_bootstrap_admin_password").read_text(encoding="utf-8").strip()
            print("bootstrap admin:", delete_bootstrap_admin(f"http://localhost:{KC_HTTP_PORT}", "tmpadmin", secret))
        return rc
    if command == "down":
        return compose("down")  # deliberately no -v: removing the pg-data volume is an owner-run decision
    if command == "status":
        return compose("ps")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
